sudo: required

language: php
php: 7.0

env:
  global:
    - PATH="$TRAVIS_BUILD_DIR/vendor/bin:$PATH"

before_install:
  - sudo curl -L https://github.com/docker/compose/releases/download/1.22.0/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
  - |
    # Remove Xdebug for a huge performance increase:
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi

install:
  - composer install --no-interaction
  - sudo ./ci/test-env-install.sh

before_script:
  - composer validate
  - ./ci/prepare.sh

script:
  - sudo ./vendor/bin/behat
  - ./ci/test-commands.sh

after_script:
  - cat /opt/easyengine/install.log
  - cat /opt/easyengine/ee.log

jobs:
  include:
    - stage: deploy
      env: DEPLOY_BRANCH=master-v4
      after_success: ./ci/deploy.sh

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email:
    on_success: never
    on_failure: change

addons:
  apt:
    packages:
      - docker-ce
